openapi: 3.0.0
info:
  description: ""
  title: Youless energy monitor
  version: 0.1.5
servers:
- description: Local device
  url: http://192.168.178.206/
paths:
  /e:
    get:
      description: |
        The url "/e" will output the same values as being used to upload and are thus firmware dependant. These were probably used for debugging, but can also be used for other applications like connecting to Domoticz or OpenHab.
      operationId: GetUploadedValues
      responses:
        "200":
          content:
            appliation/json:
              schema:
                $ref: '#/components/schemas/GetUploadedValuesResponse'
          description: Ok
      summary: Uploaded Values
  /a:
    get:
      description: Basic status info
      parameters:
      - explode: true
        in: query
        name: f
        required: false
        schema:
          $ref: '#/components/schemas/OutputFormat'
        style: form
      responses:
        "200":
          content:
            appliation/json:
              schema:
                $ref: '#/components/schemas/BasicStatusInfo'
            text/plain: {}
          description: Ok
  /d:
    get:
      description: Device info
      responses:
        "200":
          content:
            appliation/json:
              schema:
                $ref: '#/components/schemas/DeviceSchema'
          description: Ok
components:
  schemas:
    DeviceSchema:
      properties:
        model:
          type: string
        mac:
          type: string
      type: object
    OutputFormat:
      enum:
      - j
      type: string
    GetUploadedValuesResponse:
      items:
        $ref: '#/components/schemas/UploadedValues'
      type: array
    UploadedValues:
      properties:
        tm:
          description: |
            unix-time-format (1489333828 => Sun, 12 Mar 2017 15:50:28 GMT)
          type: int64
        net:
          description: |
            Netto counter, as displayed in the web-interface of the LS-120. It seems equal to: p1 + p2 - n1 - n2 Perhaps also includes some user set offset.
          format: float
          type: number
        pwr:
          description: Actual power use in Watt (can be negative)
          type: integer
        p1:
          description: P1 consumption counter (low tariff)
          format: float
          type: number
        p2:
          description: P2 consumption counter (high tariff)
          format: float
          type: number
        n1:
          description: N1 production counter (low tariff)
          format: float
          type: number
        n2:
          description: N2 production counter (high tariff)
          format: float
          type: number
        gas:
          description: counter gas-meter (in m^3)
          format: float
          type: number
        cs0:
          description: |
            kWh counter of S0 input
          format: float
          type: number
        ps0:
          description: |
            Computed power
          type: integer
        ts0:
          description: |
            Unix timestamp of the last S0 measurement.
          type: int64
        gts:
          description: |
            Last timestamp created by the 'smart meter'. "1711032100" = 2017/11/03 21:00 (yyMMddhhmm) Can be used to see if P1 communication fails.
          type: integer
      type: object
    BasicStatusInfo:
      properties:
        cnt:
          description: counter in kWh
          type: string
        pwr:
          description: Power consumption in Watt
          type: integer
        lvl:
          description: moving average level (intensity of reflected light on analog
            meters)
          type: integer
        dev:
          description: deviation of reflection
          type: string
        det:
          type: string
        con:
          description: connection status
          type: string
        sts:
          description: Time until next status update with online monitoring
          type: string
        cs0:
          description: kWh counter of S0 input
          type: string
        ps0:
          description: Computed power
          type: integer
        raw:
          description: raw 10-bit light reflection level (without averaging)
          type: integer
      type: object
