name: openapi_generator
on:
  push:
    branches:
      - openapi-generator
jobs:
  tag_repo:
    name: Generate a new GO client based on the openapi.json specification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code of the current version
        uses: actions/checkout@v2
        with:
          ref: go-client
          path: client
      - name: Checkout the openapi specification
        uses: actions/checkout@v2
        with:
          path: generator
      - name: Update client code
        run: |
            export VERSION=v$(python3 -c "import json; print(json.load(open('generator/openapi.json'))['info']['version'])")
            echo $VERSION
            find -path './client/*' ! -path "*/.git/*" -exec rm {} \;
            generator/create.sh
            echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: |
           sudo chown -R $USER:$USER ./client
           cd client
           go mod tidy
           go fmt
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
        with:
          cwd: client
          author_name: Github Action
          author_email: info@jelmert.nl
          commit: --signoff
          message: 'Next version'
          tag: $VERSION
          push: true