name: openapi_generator
on:
  push:
    branches:
      - openapi-generator
jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current client
        uses: actions/checkout@v2
        with:
          ref: master
          path: client
      - name: checkout openapi specification
        uses: actions/checkout@v2
        with:
          path: generator
      - name: Update client code
        run: |
            version=$(cat generator/version.txt)
            generator/create.sh
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
        with:
          author_name: Github Action
          author_email: info@jelmert.nl
          commit: --signoff
          cwd: generator
          message: 'Next version'
          tag: $version
          push: true